name: Taint Unit Test

on:
  push:
    branches:
      - split_out_ci
  pull_request:
    branches:
      - master

jobs:
  build_and_run_taint_unit:
    runs-on: self-hosted
    strategy:
      matrix:
        target: [i386]

    steps:
    - name: Docker login
      run: docker login -u pandare -p ${{secrets.pandare_dockerhub}}

    - name: Fetch pre-built bionic docker container
      run: docker pull pandare/panda:latest

    - name: Download docker/update.sh script from this commit
      run: wget "https://raw.githubusercontent.com/panda-re/panda/${GITHUB_SHA}/panda/docker/update.sh"

    #-v '$(pwd)/update.sh:/update.sh'
    # sed -i '/^\s*$/d' taint2_log;
    # cat taint2_log;
    - name: Start container, run update.sh clean build, and run taint unit tests
      run: >-
        docker run --name panda_test_${{ matrix.target }}_${GITHUB_RUN_ID}
        --mount type=bind,source="$(pwd)"/update.sh,target=/update.sh
        --mount type=bind,source=/home/panda/regdir/qcows/wheezy_panda2.qcow2,target=/home/panda/regdir/qcows/wheezy_panda2.qcow2
        --rm -t pandare/panda bash -c
        "cp /update.sh /panda/update.sh;
        chmod u+x /panda/update.sh;
        /panda/update.sh $GITHUB_REF clean;
        git clone https://github.com/panda-re/panda_test;
        cd ./panda_test/tests/taint2;
        python3 taint2_${{ matrix.target }}_record.py;
        python3 taint2_${{ matrix.target }}_replay.py;
        echo "Failures:";
        grep 'fail' taint2_log;"

    - name: Cleanup images
      run: docker system prune -af --volumes